
configfile: "../../config/config.yaml"

include: "rules/picrust.smk"

rule all:
	input:
		expand(rules.functional_add_descriptions.output, trait = ["16S", "EC", "KO", "TIGRFAM"]),
		rules.pathway_add_descriptions.output



