
configfile: "../../config/config.yaml"

include: "rules/picrust.smk"

rule all:
	input:
		expand(rules.functional_add_descriptions.output, trait = ["EC", "KO", "TIGRFAM"]),
		expand(rules.pathway_add_descriptions.output, trait = ["EC"])
