
import pandas as pd

configfile: "../../config/config.yaml"

samples = pd.read_csv(config["metadata"], sep = "\t", index_col = 0).index.tolist()
print(samples)

include: "rules/preprocessing.smk"
include: "rules/q2_denoising.smk"
include: "rules/taxonomy.smk"

def determine_all_output():
	# before highest read
	if config["read_depth"]["highest"] == 0:
		results = [
			rules.feature_table_summarize.output,
			rules.feature_table_tabulate_seqs.output,
			rules.metadata_tabulate_taxonomy.output,
			rules.vis_filter_table_nonmicrobial.output,
			rules.phylogeny_midpoint_root.output
		]
		print("If all done, then modify config.yaml, read_depth, highest")
	# before lowest read
	elif config["read_depth"]["lowest"] == 0:
		results = [
			rules.mock_diversity_alpha_rarefaction.output
		]
		print("If all done, then set config.yaml, read_depth, lowest")
	# after lowest read
	else:
		seqdepth = config["read_depth"]["lowest"]

		results = [
			rules.taxa_barplot.output,
			rules.diversity_alpha_rarefaction.output,
			rules.core_metrics_phylogenetics.output
		]
	return results
	
rule all:
	input:
		determine_all_output()

