###
metadata:
  input_folder/metadata.csv
classifier:
  input_folder/new_classifier.qza
fastq_path:
  input_folder/ALL_FASTQ
fwd_primer_seq:
  CCTACGGGNGGCWGCAG                # V3V4
rvs_primer_seq:
  GACTACHVGGGTATCTAATCC            # V3V4
---
