###
metadata:
    ../../input_folder/metadata.csv
classifier:
    ../../input_folder/silva-138-99-nb-classifier.qza
input_path:
    ../../input_folder
fastq_dir_path:
    ../../input_folder/ALL_FASTQ
fwd_primer_seq:
    CCTACGGGNGGCWGCAG                # V3V4
rvs_primer_seq:
    GACTACHVGGGTATCTAATCC            # V3V4
read_depth:
    highest:
        117445
    lowest:
        107128
dna_sequences_path:
    ../main_16S/results/dna-sequences.fasta
feature_table_path:
    ../main_16S/results/feature-table.biom
ancom:
    - organism
...
